SELECT * FROM giftList.toys;

INSERT INTO toys (id, brand, category, model, age, price, image, link) VALUES
(1, 'LEGO', 'lego', 'Castillo Helado de Elsa', 3, '44.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDI3MjkwfGltYWdlL2pwZWd8YUdRMUwyZ3laUzh4TXpZMU1UUXhORGswTVRjeU5nfGYxZDExZGM0MDBkZGFlYjBjNjNiZmY3MmI3MmVkYTU0NTUxOTM0NjMyNDlkZmUzMjZmYWRjMmNlMWJjZTUzOTU', 'https://www.toysrus.es/LEGO-Disney-Frozen-Castillo-Helado-de-Elsa-43238/p/K1059828');

INSERT INTO toys (id, brand, category, model, age, price, image, link)
VALUES
(2, 'LEGO', 'lego', 'Super Mario - Aventuras con Luigi pack inicial', 5, '59.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDQ1MjQ5fGltYWdlL2pwZWd8YURrMkwyZ3dPUzh4TURrMU56ZzBOak14TlRBek9BfGRkODY0ZjVmYjhmMWZmODIxMmFjY2Q2NzVlYjNhZGMyZDJiNjJlYTU0OTc2NTljNWE5MzgwMmNmNDdhZWFkZDY', 'https://www.toysrus.es/LEGO-Super-Mario-Aventuras-con-Luigi-pack-inicial-71387/p/K1028157'),
(3, 'LEGO', 'lego', 'Friends - Vehículo de plantación de árboles', 5, '29.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDQ4MjE0fGltYWdlL2pwZWd8YURSa0wyZzRPUzh4TVRrME1USXdOekF4TlRRMU5BfDMxNDU4NTQ1ZTdkNDg3MTlhYWE2YmUzYzA1NjdhMjNjZDVhZTk2MGJmYzQwMjU4YjFhNDcxN2I5OTI2YTg1MWQ', 'https://www.toysrus.es/LEGO-Friends-Veh%C3%ADculo-de-plantaci%C3%B3n-de-%C3%A1rboles-41707/p/K1034773'),
(4, 'LEGO', 'lego', 'Juguete de construcción huerto orgánico con piezas apilables y frutas-vegetales', 1, '44.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDM4MjEzfGltYWdlL2pwZWd8YUdJMUwyZ3pZaTh4TWpjeE5USTNNRGN6TXpnMU5BfDU5MTBmNGRjNWFkYWMwYzQ3ZjBjZWU5YTQyM2I1ZTI5NjFkODMwOTg5N2VkZDJjZTZjNDZlNjczMzUwMzMwMjA', 'https://www.toysrus.es/LEGO-Juguete-de-construcci%C3%B3n-huerto-org%C3%A1nico-con-piezas-apilables-y-frutas-vegetales%2C-10984/p/K1047505');

INSERT INTO toys (id, brand, category, model, age, price, image, link)
VALUES
(5, 'HOT WHEELS', 'cars', 'Hot Wheels Pista Acrobacias en Llamas con vehículo incluido', 8, '39.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDE2NTUyfGltYWdlL2pwZWd8YUdJMUwyaGhOUzh4TWpjeU1qUXpNREF4TnpVMk5nfGRkNDE5ZDRiNGYyMGYxMjQ4NTkyZjQ4ZmZjNmJlYTZkMzdmMDNkZTY1ZGUyYTMwMzAyNTM5MDU4ODg3MGM1YmQ', 'https://www.toysrus.es/Hot-Wheels-Hot-Wheels-Pista-Acrobacias-en-Llamas-con-veh%C3%ADculo-incluido/p/K1047043'),
(6, 'HOT WHEELS', 'cars', 'Camión T-Rex definitivo y pista para coches de juguete con 2 vehículos incluidos', 3, '99.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDI2MDU0fGltYWdlL2pwZWd8YUdWakwyZ3daaTh4TWpnM056STVPREV3TmpNNU9BfDNiYTlhYTk0MzM3MzYyNDMwYWY0ZDY1MjIyY2U1YTAyMDBhNGIxMjViODZmYTI2NjE4NTU1YzA4NmNmODZmNmE', 'https://www.toysrus.es/Hot-Wheels-Cami%C3%B3n-T-Rex-definitivo-y-pista-para-coches-de-juguete-con-2-veh%C3%ADculos-incluidos-%E3%85%A4/p/K1054883'),
(7, 'HOT WHEELS', 'cars', 'Hot Wheels City - Mordisco del tiburón', 3, '69.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDMxMjI3fGltYWdlL2pwZWd8YURFekwyaGxaUzh4TWpJeE16a3dOakEwTnpBd05nfDBjMjlhOTE1MDdmNmJiMjM1ZDdiNjQ4OTRlOWZiYTIxYzZhYjI5Yjk2ZWIyZDI5MzdiNDMxNmIwOTdmNTc3NDY', 'https://www.toysrus.es/Hot-Wheels-City-Mordisco-del-tibur%C3%B3n/p/K1040662'),
(8, 'HOT WHEELS', 'cars', 'Hot Wheels - Pack 10 Vehículos (varios modelos)', 3, '24.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDMyMTg3fGltYWdlL2pwZWd8YURFeEwyaGlPQzh4TVRZeU9EazJNalF4TkRZeU1nfGUzZGM2OGY0NGI1YWZjYWVmMjVkNTczMGQ5Nzc0MGI4ZWRmMzFhMzQyZTk1NzEwZDZiNmUyM2UwZDgwZDg0MzE', 'https://www.toysrus.es/Hot-Wheels-Pack-10-Veh%C3%ADculos-(varios-modelos)/p/K267058'),
(9, 'CARS', 'cars pixar', 'Mini Racers (varios modelos)', 3, '3.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDUyMzQ0fGltYWdlL2pwZWd8YURrNEwyZ3dNQzh4TVRRM01URTRNalkxT1RZeE5BfDRjMGQ3YjQ3Mjg3Yzk1YmNjNWQ0ZGQwNzljOTgwN2M5ZmE5YmJmYTQwN2QwYzllMzU2ZjI0YjgxOGNmMjM5MDE', 'https://www.toysrus.es/Cars-Mini-Racers-(varios-modelos)/p/K78045');


INSERT INTO toys (id, brand, category, model, age, price, image, link)
VALUES
(10, 'CARS', 'cars pixar', 'Vehículo juguete Monster Truck Acrobático', 3, '24.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDI4OTM1fGltYWdlL2pwZWd8YURNd0wyZ3dNUzh4TXpnM09USTRNVGMwTlRrMU1BfDgxNzlhNDI5MThjYTRiYmQyZjU3NTVjY2ZmMzljZTRmNDA0OGU2MDBiNjY4NzNhNmE3MDE4ZTg1OTJjMmUxZWM', 'https://www.toysrus.es/Mattel-Cars-Veh%C3%ADculo-juguete-Monster-Truck-Acrob%C3%A1tico-%E3%85%A4/p/K1060460'),
(11, 'CARS', 'cars pixar', 'Camión Mack transporte de coches', 3, '24.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDE5NTkwfGltYWdlL2pwZWd8YURReEwyZzNNeTh4TWpBeE9EQTFOelF4TWpZek9BfDk1ZWEwNWQ5ZWVhYmY4ZTllYTY3YzcwZTc4NTRmN2I2YTUyY2E2ZWJiNzY5NzhjMDM5ZDdjOTgzMzIyYjBkYzA', 'https://www.toysrus.es/Cars-Cami%C3%B3n-Mack-transporte-de-coches/p/K1034667'),
(12, 'CARS', 'cars pixar', 'Coche de Cars 3 (varios modelos)', 3, '9.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDQzMjMwfGltYWdlL2pwZWd8YUdFMEwyZzJaUzg0T1RNNE56QXhNVGt6TWpRMnw4ZTVlYTFhMzQzMTEwYzQ5MDlhZDA3YzRjMWU4M2MxMjA4ZTcwZmM0MmFjZmM0N2M3ZTAyNGUzMjBiYzY3ZGQ2', 'https://www.toysrus.es/Cars-Coche-de-Cars-3-(varios-modelos)/p/K206199');

INSERT INTO toys (id, brand, category, model, age, price, image, link)
VALUES
(13, 'NENUCO', 'babies', 'Pañal mágico', 3, '46.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDI5NzU3fGltYWdlL2pwZWd8YUdVMUwyaGlOUzh4TWpFNU1qWTJOVE0zTURZMU5BfGNlY2Y2NTVmOWEwZDI0NTQzYmJmMDliYjg4ZTFhNzJkZWZkOWUyODcxZDc5MjJiMzVlNmYyMDVjNDJjODVhY2M', 'https://www.toysrus.es/Nenuco-Pa%C3%B1al-m%C3%A1gico/p/K1041052'),
(14, 'NENUCO', 'babies', 'Muñeco Blandito 5 Funciones Rosa', 1, '18.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDMyNzY4fGltYWdlL2pwZWd8YURNNEwyaGtNUzg0T0RZeE9ETXdNVGcwT1Rrd3xiODg2OWRhYWYzODZkODQ3ODg3MjAyMzA4MWQ5MjRjOGY4MTUzZWQyMjQwZGRhMTljYjMwZWMxYTQ4ZGEyZGIz', 'https://www.toysrus.es/Nenuco-Mu%C3%B1eco-Blandito-5-Funciones-Rosa/p/K170148'),
(15, 'NENUCO', 'babies', 'Muñeco ¿Estás malito?', 3, '39.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDIzMTI4fGltYWdlL2pwZWd8YUdNNUwyZzRPUzh4TVRFMk56ZzFOamd5TURJMU5BfDk2ZDc5MDZmZjc2YWJiYWE0NDZlZDdmOWRmYjBmYmFmZWRjNDUxNjEyMTNkMTE2MDZkZGM1YzBkOTEyYjcxZTQ', 'https://www.toysrus.es/Nenuco-Mu%C3%B1eco-%C2%BFEst%C3%A1s-malito%3F/p/K1030819');

INSERT INTO toys (id, brand, category, model, age, price, image, link)
VALUES
(16, 'NENUCO', 'babies', 'La cuna que te ayuda', 1, '74.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDMwMzc4fGltYWdlL2pwZWd8YURCa0wyaG1ZUzh4TWpFNU1qWTROVGd4TnpnNE5nfDIzYWU1ZDNlOWFhMjFhZmQyYzUzZjIzNDIwNmRkMWI2ZDA0ZGFlNTMzODFmOTdmM2NlMTIwNzA2YmRjN2I3M2Y', 'https://www.toysrus.es/Nenuco-La-cuna-que-te-ayuda/p/K1041056'),
(17, 'BARBIE', 'barbies', 'Pack muñeca con mascotas', 3, '29.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDE4NDAyfGltYWdlL2pwZWd8YURFeEwyaG1OUzh4TWpBeE1EUXlNVGczT0RneE5BfDkwODhmYWE5ZmM3MWFmMGNkNTAzMzFlNTMxMjgyMmJiZjBhZjE0NmI3OThlYzQwMzNlNWE1OGQ0YWJhMmZkNzQ', 'https://www.toysrus.es/Barbie-Pack-mu%C3%B1eca-con-mascotas/p/K1036814');

INSERT INTO toys (id, brand, category, model, age, price, image, link)
VALUES
(18, 'BARBIE', 'barbies', 'Pediatra - Muñeca Yo Quiero Ser', 3, '24.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDE3NTg2fGltYWdlL2pwZWd8YUdOakwyZzJZUzh4TWpJeE5ETXlPRFl5TXpFek5BfGJhZjQwY2MyZTJmZjg0ZmYxY2EwOGMzNjI1ZjQ1OTc4ZTc4ZTRlODMxMGQ5MTY4MTRhYzk1YzVhZjc4ODhkNGY', 'https://www.toysrus.es/Barbie-Pediatra-Mu%C3%B1eca-Yo-Quiero-Ser/p/K1041431'),
(19, 'BARBIE', 'barbies', 'Supermercado', 3, '44.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDM0MDY4fGltYWdlL2pwZWd8YURaaUwyZzBaUzg1TXpVNE16RTJOVFk0TmpBMnxmYTRkZjBmNDFlZmJkZGYyNTY2MmQ2NWQ0Nzk5ZGY3MzA5MzM1OTJhOTdiZTNhYjViMGRhMTVhMjAzYzRhMTM5', 'https://www.toysrus.es/Barbie-Supermercado/p/K960783'),
(20, 'BARBIE', 'barbies', 'Muñeca Barbie y restaurante Cook´n Grill', 3, '79.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDM4NjYwfGltYWdlL2pwZWd8YUdFMkwyaGxOaTh4TVRNNE16RTFNelkxTlRnek9BfDYzMmZjNTMwZjU4YzA5YzhjNjQyZmMxMjk0YmJkMmM3ZWE5OTcwNzQ3ZjNjMWZhMGY3MWViNzc1ZjJjMGVkMDQ', 'https://www.toysrus.es/Barbie-Mu%C3%B1eca-Barbie-y-restaurante-Cook%C2%B4n-Grill/p/K1031260');

INSERT INTO toys (id, brand, category, model, age, price, image, link)
VALUES
(22, 'PLAY-DOH', 'play-doh', 'Kit veterinario', 3, '24.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDU0Mjg5fGltYWdlL2pwZWd8YURBMkwyZ3dPUzh4TVRnNU1qUXdPRGd4TVRVMU1BfDhkZDY1YjBlNDdjNjc2OTFlMzNiMDE5MTExYThkNmZjZTcxMmQ3ZDdkNDUyY2ViNGFlNDc3YjQ5MTNjOWIxN2Y', 'https://www.toysrus.es/Play-Doh-Kit-veterinario/p/K1036673'),
(23, 'PLAY-DOH', 'play-doh', 'Rex el dino glotón', 3, '23.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDM1ODQ5fGltYWdlL2pwZWd8YURBNEwyZ3daaTh4TURreE9ERTRNREk1TURVNU1BfDc0NDQ5YWY5ZjUwMmEwYzQ0NWMxMjk5NWVmZGFkZDRmNGVmYzEzYWRlY2M4YTZkZTViZjIxNmM0ODM1ZWNjYjI', 'https://www.toysrus.es/Play-Doh-Rex-el-dino-glot%C3%B3n/p/K1026194'),
(24, 'PLAYMOBIL', 'playmobil', 'Playmobil 1.2.3 - Granja Maletín', 3, '39.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDM5NTgzfGltYWdlL2pwZWd8YUdRNUwyZzJaaTg0TnprNE16azNNRGN4TXprd3xiM2U5NmZkOWI1MzQ5NTNhOTc5MzM2YWYxZDA0M2IzNmFhOWM1MmQyOGVhZDE5Y2I4Y2I0NGM5MjJmYjNlNTcz', 'https://www.toysrus.es/Playmobil-1-2-3-Granja-Malet%C3%ADn-6962/p/K367214'),
(25, 'PLAYMOBIL', 'playmobil', 'Helicóptero de policía: persecución del vehículo huido', 5, '64.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDU5MTAzfGltYWdlL2pwZWd8YURVeUwyZ3haUzh4TURnek16UTFNVEk0TmpVMU9BfGViODRkYTE5OGVkZWMyMWViY2FhNzMxOWE5MGI5NGQ4Mjk2MzQ3ZWNjODNmMGViOTMwOTVlYTkwMTZjYzc4YzU', 'https://www.toysrus.es/Playmobil-Helic%C3%B3ptero-de-polic%C3%ADa%3A-persecuci%C3%B3n-del-veh%C3%ADculo-huido-70575/p/K1025688'),
(26, 'PLAYMOBIL', 'playmobil', 'Casa de campo y animales de granja Playmobil Country', 3, '59.99', 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDUyOTE1fGltYWdlL2pwZWd8YUdJM0wyaGxOeTh4TWpjMU16VXdOVFU0TXpFek5BfDIyZjM5ZWMxZWIxZWQ0YTJmYzAxYzM1MjJlZTNmM2RkNTZjMGY5MWEwOTBjMzVjMzEyNDhmNmJkYzJmNWJlZGI', 'https://www.toysrus.es/Playmobil-Casa-de-campo-y-animales-de-granja-Playmobil-Country-%E3%85%A4/p/K1048335');

INSERT INTO toys (id, brand, category, model, age, price, image, link)
VALUES (21, 'PLAY-DOH', 'play-doh', 'Pack 20 Botes', 3, 17.99, 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDQ3NjQwfGltYWdlL2pwZWd8YURVNEwyZ3hZUzg0T0RreU16SXhOekkyTkRrMHwzNTBjZDYzMjA1NjE1Y2QxMTA5MmQ2YWZkZTNiM2EzNzk4ZGQ5NDZiZGNmNWNjMDVmY2EwZTQxM2E4ZmE3N2Zl', 'https://www.toysrus.es/Play-Doh-Pack-20-Botes/p/K13579');

INSERT INTO toys (id, brand, category, model, age, price, image, link)
VALUES (27, 'PLAYMOBIL', 'playmobil', 'Playmobil City Life: Abuelos y Nieto, Set', 3, 11.99, 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDQ5NDgxfGltYWdlL2pwZWd8YURKaEwyaGhNeTh4TWpjM016STNPREk0TlRnMU5BfDMzZGQ1MDg4ZGY3ZDdkMmE3NWI0MTRhM2EzYWMxYjk5Nzg0Y2NmZWNhN2EzOWY4OGI5NThlZjllY2UyYWYxODY', 'https://www.toysrus.es/Playmobil-Playmobil-City-Life%3A-Abuelos-y-Nieto%2C-Set-70990-%E3%85%A4/p/K1048304'),
       (28, 'CLEMENTONI', 'puzzle', 'Patrulla Canina - Puzzle infantil progresivo 10 en 1 de la Patrulla Canina', 3, 17.99, 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDYyMDI4fGltYWdlL2pwZWd8YURNeEwyaG1OaTh4TWprek16Z3dOemd6TXpFeE9BfDlkMzdkZWVlNTMyY2RhMGI3MWNmMDEzODI4Y2MyM2FkNjFkNjAyNmNlOWY2Y2FlYTQ2YzdkYzg5NWU1YWUxOTk', 'https://www.toysrus.es/Clementoni-Patrulla-Canina-Puzzle-infantil-progresivo-10-en-1-de-la-Patrulla-Canina-%E3%85%A4/p/K1046806'),
       (29, 'EDUCA BORRAS', 'puzzle', 'Los Vengadores - Puzzle 2x48 Piezas', 3, 11.99, 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDU5ODUzfGltYWdlL2pwZWd8YURCbEwyZ3hZeTg0T0RrMk5ERTJOREUxTnpjMHw2MjUyMjFmODEyYzVlOTk2OWZlNjY5Mzk0N2M4OTc5ZjExNjg1NTFlNzUzZDM3NzRjZTkyYzVmYWNiMmNhNGM3', 'https://www.toysrus.es/Educa-Borr%C3%A1s-Los-Vengadores-Puzzle-2x48-Piezas/p/K110879B'),
       (30, 'RAVENSBURGER', 'puzzle', 'Disney - Puzzle 2x24 pzs Frozen II', 5, 12.99, 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDQwMTM4fGltYWdlL2pwZWd8YURnMUwyZ3lNaTh4TWpVeU9EQXhNVEF4T0RJM01BfDBhYzBiMjA5N2U0MzdkZTIxNTNkODAxZjY3MDViM2Y1MzhlN2E5MGFjNDkyY2VkN2I2OWY4NDIwNDE2ODlkNDU', 'https://www.toysrus.es/Ravensburger-Disney-Puzzle-2x24-pzs-Frozen-II/p/K1043489'),
       (31, 'RAVENSBURGER', 'puzzle', 'Princesas Disney - Pack 2 puzzles 24 piezas', 3, 12.99, 'https://www.toysrus.es/medias/?context=bWFzdGVyfHByb2R1Y3RfaW1hZ2VzfDQwODM5fGltYWdlL2pwZWd8YURVNUwyZzVOeTh4TWpVME16TTVNamczTkRVeU5nfGNiYjhjYjVkMWRlMWFiNmI1YTA4ODdhMDg1NmY1NjVlNTY2YTFkNjhlOWVhNzI5ODM1NzkyM2Y1ZTViZTE4ODE', 'https://www.toysrus.es/Ravensburger-Princesas-Disney-Pack-2-puzzles-24-piezas/p/K1043486');



